[[connections]]
= Connections

R2DBC uses the `Connection` interface to define a logical connection API to the underlying data source.
The structure of a connection depends on the actual requirements of the data source and how the driver implements these.

The data source can be an RDBMS, a stream-oriented data system, or some other source of data with a corresponding R2DBC driver.
A single application that uses R2DBC SPI can maintain multiple connections to either a single data source or across multiple data sources.
From a R2DBC driver perspective, a `Connection` object represents a single client session.
It has associated state information, such as user ID and what transaction semantics are in effect.
A `Connection` object is not safe for concurrent state-changing by multiple subscribers.
A connection object can be shared across multiple threads that serially run operations by using appropriate synchronization mechanisms.

To obtain a connection, the application can:

* Interact with the `ConnectionFactories` class by working with one or more `ConnectionFactoryProvider` implementations.
* Directly interact with a `ConnectionFactory` implementation.

See <<overview.connection>> for more details.

[[connections.factory]]
== The `ConnectionFactory` Interface

R2DBC drivers must implement the `ConnectionFactory` interface as a mandatory part of the SPI.
Drivers can provide multiple `ConnectionFactory` implementations, depending on the protocol in use or aspects that require the use of a different `ConnectionFactory` implementation.
The following listing shows the `ConnectionFactory` interface:

.`ConnectionFactory` Interface
====
[source,java]
----
public interface ConnectionFactory {

    Publisher<? extends Connection> create();

    ConnectionFactoryMetadata getMetadata();

}
----
====

The following rules apply:

* A `ConnectionFactory` represents a resource factory for deferred connection creation.
It may create connections by itself, wrap a `ConnectionFactory`, or apply connection pooling on top of a `ConnectionFactory`.
* A `ConnectionFactory` provides metadata about the driver itself through `ConnectionFactoryMetadata`.
* A `ConnectionFactory` uses deferred initialization and must initiate connection resource allocation after requesting the item (`Subscription.request(1)`) and not upon calling `create` itself.
* Connection creation must emit exactly one `Connection` or an error signal.
* Connection creation must be cancellable (`Subscription.cancel()`).
Canceling connection creation must release ("`close`") the connection and all associated resources.
* A `ConnectionFactory` should expect that it can be wrapped.
Wrappers must implement the `Wrapped<ConnectionFactory>` interface and return the underlying `ConnectionFactory` when `Wrapped.unwrap()` gets called.

=== ConnectionFactory Metadata

`ConnectionFactory` instances are required to expose metadata to identify the driver (`ConnectionFactory`) and its capabilities.
Metadata must not require a connection to a data source.
The following listing shows the `ConnectionFactoryMetadata` interface:

.`ConnectionFactoryMetadata` Interface
====
[source,java]
----
public interface ConnectionFactoryMetadata {

    String getName();

}
----
====

See the R2DBC SPI Specification for more details.

[[connections.factory.discovery]]
== `ConnectionFactory` Discovery Mechanism

As part of its usage, the `ConnectionFactories` class tries to load any R2DBC driver classes referenced by the `ConnectionFactoryProvider` interface listed in the Java Service Provider manifests that are available on the classpath.

Drivers must include a file called `META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider`.
This file contains the name of the R2DBC driver's implementation (or implementations) of `io.r2dbc.spi.ConnectionFactoryProvider`.
To ensure that drivers can be loaded by using this mechanism, `io.r2dbc.spi.ConnectionFactoryProvider` implementations are required to provide a no-argument constructor.
The following listing shows a typical `META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider` file:

.META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider file contents
====
[source]
----
com.example.ConnectionFactoryProvider
----
====

The following listing shows the `ConnectionFactoryProvider` interface:

.`ConnectionFactoryProvider` Interface
====
[source,java]
----
public interface ConnectionFactoryProvider {

    ConnectionFactory create(ConnectionFactoryOptions connectionFactoryOptions);

    boolean supports(ConnectionFactoryOptions connectionFactoryOptions);

    String getDriver();

}
----
====

`ConnectionFactories` uses a `ConnectionFactoryOptions` object to look up a matching driver by using a two-step model:

. Look up an adequate `ConnectionFactoryProvider`.
. Obtain the `ConnectionFactory` from the `ConnectionFactoryProvider`.

`ConnectionFactoryProvider` implementations are required to return a `boolean` indicator whether or not they support a specific configuration represented by `ConnectionFactoryOptions`.
Drivers must expect any plurality of `Option` instances to be configured.
Drivers must report that they support a configuration only if the `ConnectionFactoryProvider` can provide a `ConnectionFactory` based on the given `ConnectionFactoryOptions`.
A typical task handled by `supports` is checking driver and protocol options.
Drivers should gracefully fail if a `ConnectionFactory` creation through `ConnectionFactoryProvider.create(…)` is not possible (i.e. when required options were left unconfigured).
The `getDriver()` method reports the driver identifier that is associated with the `ConnectionFactoryProvider` implementation to provide diagnostic information to users in misconfiguration cases.

See the R2DBC SPI Specification and <<overview.connection.discovery,ConnectionFactory Discovery>> for more details.

[[connections.factory.options]]
== The `ConnectionFactoryOptions` Class

The `ConnectionFactoryOptions` class represents a configuration for a request a `ConnectionFactory` from a `ConnectionFactoryProvider`.
It enables the <<overview.connection, programmatic connection creation>> approach without using driver-specific classes.
`ConnectionFactoryOptions` instances are created by using the builder pattern, and properties are configured through `Option<T>` identifiers.
A `ConnectionFactoryOptions` is immutable once created.
`Option` objects are reused as part of the built-in constant pool.
Options are identified by a literal.

`ConnectionFactoryOptions` defines a set of well-known options:

.Well-known Options
|===
|Constant |URL Literal |Type |Description

|`SSL`
|`ssl`
|`java.lang.Boolean`
|Whether the connection is configured to require SSL.

|`DRIVER`
|`driver`
|`java.lang.String`
|Driver identifier.

|`PROTOCOL`
|`protocol`
|`java.lang.String`
|Protocol details, such as the network protocol used to communicate with a server.

|`USER`
|`user`
|`java.lang.String`
|User account name.

|`PASSWORD`
|`password`
|`java.lang.CharSequence`
|User or database password.

|`HOST`
|`host`
|`java.lang.String`
|Database server name.

|`PORT`
|`port`
|`java.lang.Integer`
|Database server port number.

|`DATABASE`
|`database`
|`java.lang.String`
|Name of the particular database on a server.

|`CONNECT_TIMEOUT`
|`connectTimeout`
|`java.time.Duration`
|Connection timeout to obtain a connection.

|`LOCK_WAIT_TIMEOUT`
|`lockWaitTimeout`
|`java.time.Duration`
|Lock acquisition timeout.

|`STATEMENT_TIMEOUT`
|`statementTimeout`
|`java.time.Duration`
|Statement timeout.
|===

The following rules apply:

* The set of options is extensible.
* Drivers can declare which well-known options they require and which they support.
* Drivers can declare which extended options they require and which they support.
* Drivers should not fail in creating a connection if more options are declared than the driver consumes, as a `ConnectionFactory` should expect to be wrapped.
* Connection URL Parsing cannot access `Option` type information `T` due to Java's type erasure.
Options obtained by URL parsing beyond well-known keys are represented as `String` values.

The following example shows how to set options for a `ConnectionFactoryOptions`:

.Configuration of `ConnectionFactoryOptions`
====
[source,java]
----
ConnectionFactoryOptions options = ConnectionFactoryOptions.builder()
    .option(ConnectionFactoryOptions.HOST, "…")
    .option(Option.valueOf("tenant"), "…")
    .option(Option.sensitiveValueOf("encryptionKey"), "…")
    .build();
----
====

See the R2DBC SPI Specification for more details.

[[connections.factory.create]]
== Obtaining `Connection` Objects

Once a `ConnectionFactory` is bootstrapped, connections are obtained from the `create()` method.
The following example shows how to obtain a connection:

.Obtaining a `Connection`
====
[source,java]
----
// factory is a ConnectionFactory object
Publisher<? extends Connection> publisher = factory.create();
----
====

The connection is active once it has been emitted by the `Publisher` and must be released ("`closed`") once it is no longer in use.

[[connections.metadata]]
== Connection Metadata

Connections are required to expose metadata about the database they are connected to.
Connection Metadata is typically discovered dynamically based from information obtained during `Connection` initialization.

.`ConnectionMetadata` Interface
====
[source,java]
----
public interface ConnectionMetadata {

    String getDatabaseProductName();

    String getDatabaseVersion();

}
----
====

See the R2DBC SPI Specification for more details.

[[connections.validate]]
== Validating `Connection` Objects

The `Connection.validate(…)` method indicates whether the `Connection` is still valid.
The `ValidationDepth` argument passed to this method indicates the depth to which a connection is validated: `LOCAL` or `REMOTE`.

* `ValidationDepth.LOCAL`: Requests client-side-only validation without engaging a remote conversation to validate a connection.
* `ValidationDepth.REMOTE`: Initiates a remote validation by issuing a query or other means to validate a connection and the remote session.

If `Connection.validate(…)` emits `true`, the `Connection` is still valid.
If `Connection.validate(…)` emits `false`, the `Connection` is not valid, and any attempt to perform database interaction fails.
Callers of this method do not expect error signals or empty completion.

[[connections.close]]
== Closing `Connection` Objects

Calling `Connection.close()` prepares a close handle to release the connection and its associated resources.
Connections must be closed to ensure proper resource disposal.
You can use `Connection.validate(…)` to determine whether a `Connection` has been closed or is still valid.
The following example shows how to close a connection:

.Closing a `Connection`
====
[source,java]
----
// connection is a ConnectionFactory object
Publisher<Void> close = connection.close();
----
====

See the R2DBC SPI Specification for more details.

[[connections.lock-acquisition-timeout]]
== Limiting the time for lock acquisition

The lock acquisition timeout can be configured on the `Connection` level allowing to associate the connection with a lock acquisition limit.
The default lock acquisition timeout is vendor-specific and can be specified for new connections through <<connections.factory.options, connection factory options>>.

If the timeout is exceeded, a `R2dbcTimeoutException` is raised to the client.
Support for transaction-bound timeouts through <<transactions.transaction-definition.usage,`TransactionDefinition`>> is subject to vendor-specific availability.

[[connections.statment-timeout]]
== Limiting execution time for statements

The statement timeout can be configured on the `Connection` level allowing to associate the connection with a timeout limit.
By default there is no limit on the amount of time allowed for a running statement to complete unless specified through <<connections.factory.options, connection factory options>>.
The minimum amount of time can be used to either let the data source cancel the statement or attempt a client-side cancellation.

Once the data source has had an opportunity to process the request to terminate the running command, a `R2dbcTimeoutException` is raised to the client and no additional processing can occur against the previously running command without re-executing a statement.

The timeout applies to statements through a combination of `Statement#execute`, `Batch#execute` and `Result` consumption.
In the case of `Batch`/`Statement` batching, it is vendor-specific whether the timeout is applied to individual SQL commands or the entire batch.

Support for transaction-bound timeouts through <<transactions.transaction-definition.usage,`TransactionDefinition`>> is subject to vendor-specific availability.
