[[goals]]
= Goals

This section outlines the goals for R2DBC and the design philosophy for its SPI.
It covers the following topics:

* <<goals.enabling>>
* <<goals.reactive-jvm>>
* <<goals.standardization>>
* <<goals.vendor-specifics>>
* <<goals.sql>>
* <<goals.kiss>>
* <<goals.foundation>>
* <<goals.requirements>>

[[goals.enabling]]
== Enabling Reactive Relational Database Connectivity

The R2DBC specification aims for establishing an interface that has a minimal API surface to integrate with relational databases by using a reactive programming model.
The most significant goals are honoring and embracing the properties of reactive programming, including the following:

* Non-blocking I/O
* Deferred execution
* Treating application control as a series of events (data, errors, completion, and so on)
* No longer assuming control of resources but leaving resource scheduling to the runtime or platform ("`React to resource availability`")
* Efficiently using resources
* Leaving flow control to be handled by the runtime
* Stream-oriented data consumption
* Functional programming within operators
* Removing assumptions over concurrency from the programming model and leaving this aspect up the runtime
* Using back-pressure to allow flow control, deferring the actual execution and not overwhelming consumers

[[goals.reactive-jvm]]
== Fitting into Reactive JVM platforms

R2DBC aims for seamless integration of reactive JVM platforms, targeting Java as its primary platform.
R2DBC should also be usable from other platforms (such as Kotlin or Scala) without scarifying its SPI for the sake of idiomatic use on a different platform.

[[goals.standardization]]
== Offering Vendor-neutral Access to Standard Features

R2DBC SPI strives to provide access to features that are commonly found across different vendor implementations.
The goal here is to provide a balance between features that are implemented in a driver and these that are better implemented in a client library.

[[goals.vendor-specifics]]
== Embracing Vendor-specific Features

Each database comes with its own feature set and how these are implemented.
R2DBC's goal is to define a minimal standard over commonly used functionality and allow for vendor-specific deviation.
Drivers can implement additional functionality or make these transparent through the R2DBC SPI.

[[goals.sql]]
== Keeping the Focus on SQL

The focus of R2DBC is on accessing relational data from the Java programming language by using databases that provide an SQL interface with which to interact.

The goal here is not to limit implementations to relational-only databases.
Instead, the goal is to provide guidance for uniform reactive data access by using tabular data consumption patterns.

[[goals.kiss]]
== Keeping It Minimal and Simple

R2DBC does not aim to be a general-purpose data-access API.

R2DBC specializes in reactive data access and common usage patterns that result from relational data interaction.
R2DBC does not aim to abstract common functionality that needs to be re-implemented by driver vendors in a similar manner.
It aims to leave this functionality to client libraries, of which there are typically fewer implementations than drivers.

[[goals.foundation]]
== Providing a Foundation for Tools and Higher-level APIs

The R2DBC SPI aims for being primarily consumed though client library implementations.

It does not aim to be an end-user or application developer programming interface.

Having a uniform reactive relational data access SPI makes R2DBC a valuable target platform for tool vendors and application developers who want to create portable tools and applications.

[[goals.requirements]]
== Specifying Requirements Unambiguously

The requirements for R2DBC compliance should be unambiguous and easy to identify.
The R2DBC specification and the API documentation (Javadoc) clarify which features are required and which are optional.
