[[introduction]]
= Introduction

[[introduction.what-is-r2dbc]]
R2DBC stands for Reactive Relational Database Connectivity.
R2DBC started as an experiment and proof of concept to enable integration of SQL databases into systems that use reactive programming models –- Reactive in the sense of an event-driven, non-blocking, and functional programming model that does not make assumptions over concurrency or asynchronicity.
Instead, it assumes that scheduling and parallelization happen as part of runtime scheduling.

[[introduction.r2dbc-spi]]
== The R2DBC SPI

The R2DBC SPI provides reactive programmatic access to relational databases from Java and other JVM-based programming languages.

R2DBC specifies a service-provider interface (SPI) that is intended to be implemented by driver vendors and used by client libraries.
By using the R2DBC SPI, applications written in a JVM programming language can run SQL statements and retrieve results by using an underlying data source.
You can also use the R2DBC SPI to interact with multiple data sources in a distributed, heterogeneous environment.
R2DBC targets primarily, but is not limited to, relational databases.
It aims for a range of data sources whose query and statement interface is based on SQL (or an SQL-like dialect) and that represent their data in a tabular form.

A key difference between R2DBC and imperative data access SPIs is the deferred nature of execution.
R2DBC is, therefore, based on https://www.reactive-streams.org/[Reactive Streams] and uses the concepts of `Publisher` and `Subscriber` to allow non-blocking back-pressure-aware data access.

[[introduction.requirements-conventions]]
== Requirements and Conventions

R2DBC requires Java 8 as baseline and https://www.reactive-streams.org/[Reactive Streams] in terms of a reactive inter-op API.

A note about modules: R2DBC allow for deployment to JDK 9's module path ("Jigsaw").
For use in Jigsaw-enabled applications, the R2DBC SPI comes with "Automatic-Module-Name" manifest entries which define stable language-level module names ("r2dbc.spi") instead using the artifact name.
Of course, R2DBC jars keep working fine on the classpath on both JDK 8 and 9+.

R2DBC's SPI uses non-null semantics by default.
Nullable API members are annotated with `@io.r2dbc.spi.Nullable`.
This annotation and `@NonNullApi` are meta-annotated with https://jcp.org/en/jsr/detail?id=305[JSR 305] annotations (a dormant but wide-spread JSR).
JSR-305 meta-annotations let tooling vendors like IDEA or Kotlin provide null-safety support in a generic way, without having to hard-code support for R2DBC annotations.
It is not necessary nor recommended to add a JSR-305 dependency to the project classpath to take advantage of a null-safe API.

R2DBC generally uses zero-based indexes for parameter binding and columns.

[[introduction.target-audience]]
== Target Audience

This specification is targeted primarily towards:

* Vendors of drivers that implement the R2DBC SPI.
* Vendors of client implementations who wish to implement a client on top of the R2DBC SPI.
* Vendors of runtime libraries who wish to embed R2DBC into their eco-system to provide R2DBC runtime services.

This specification is also intended to offer:

* An introduction for end-users whose applications use the R2DBC SPI.
* A starting point for developers of other SPIs layered on top of the R2DBC SPI.

Code examples in this specification assume external subscription to `Publisher` objects for brevity.

[[introduction.acknowledgements]]
== Acknowledgements

The R2DBC specification work is being conducted as an effort of individuals that recognized the demand for a reactive, standardized API for relational database access.
We want to thank all https://github.com/r2dbc/r2dbc-spi/graphs/contributors[contributing members] for their countless hours of work and discussion.

Thanks also go to Ollie Drotbohm, without whom this initiative would not even exist.

[[introduction.following]]
== Following Development

For information on R2DBC source code repositories, nightly builds, and snapshot artifacts, see the https://r2dbc.io/resources/[R2DBC] homepage.
You can help make R2DBC best serve the needs of the community by interacting with developers through the community.
To follow developer activity, look for the mailing list information on the R2DBC homepage.
If you encounter a bug or want to suggest an improvement, please create a ticket on the R2DBC issue tracker.
R2DBC has an open-source organization on GitHub that bundles the various projects (SPI and drivers) under R2DBC.

To stay up to date with the latest news and announcements in the R2DBC eco system, you can subscribe to the mailing list. You can also follow the project team on Twitter (https://twitter.com/r2dbc[@R2DBC]).

[[introduction.project-metadata]]
== Project Metadata

* Version control: https://github.com/r2dbc/r2dbc-spi
* Mailing list: link:++https://groups.google.com/forum/#!forum/r2dbc++[++https://groups.google.com/forum/#!forum/r2dbc++]
* Issue tracker: https://github.com/r2dbc/r2dbc-spi/issues
* Release repository: https://repo1.maven.org/maven2
* Snapshot repository: https://oss.sonatype.org/content/repositories/snapshots
