[[out-parameter-metadata]]
= OUT Parameter Metadata

The `OutParametersMetadata` interface is implemented by R2DBC drivers to provide information about OUT parameters.
It is used primarily by libraries and applications to determine the properties of result parameters.

In cases where the result properties of an SQL statement are unknown until it is run, the `OutParametersMetadata` can be used to determine the actual properties.

`OutParametersMetadata` exposes `OutParameterMetadata` for each returned out parameter.
Drivers should provide `OutParameterMetadata` on a best-effort basis.
Out parameter metadata is typically a by-product of stored procedure execution.
The amount of available information is vendor-dependent.
Metadata retrieval can require additional lookups (internal queries) to provide a complete metadata descriptor.
Issuing queries during result processing conflicts with the streaming nature of R2DBC.
Consequently, `OutParameterMetadata` declares two sets of methods: methods that must be implemented and methods that can optionally be implemented by drivers.

== Obtaining a `OutParametersMetadata` Object

A `OutParametersMetadata` object is created during results consumption through `Result.map(…)`.
It is created once for all out parameters.
The following example illustrates retrieval and usage by using an anonymous inner class:

.Using `OutParametersMetadata` and retrieving `OutParameterMetadata`
====
[source,java]
----
// result is a Result object
result.map(new Function<Readable, Object>() {

    @Override
    public Object apply(Readable readable) {

        if (readable instanceof OutParameters) {

            OutParameters out = (OutParameters) readable;
            OutParametersMetadata md = out.getMetadata();

            OutParameterMetadata my_parameter = md.getParameterMetadata("my_parameter");
            Nullability nullability = my_parameter.getNullability();
            // …
        }
    }
});
----
====

[[outparametermetadata]]
== Retrieving `OutParameterMetadata`

`OutParameterMetadata` methods are used to retrieve metadata for a single parameter or all parameters.

* `getParameterMetadata(int)` returns the `OutParameterMetadata` by using a zero-based index.
See <<compliance.guidelines>>.
* `getParameterMetadata(String)` returns the `OutParameterMetadata` by using the parameter name.
* `getParameterMetadatas()` returns an unmodifiable collection of `OutParameterMetadata` objects.

== Retrieving General Information for a OUT Parameter

`OutParameterMetadata` declares methods to access out parameter metadata on a best-effort basis.
Out parameter metadata that is available as a by-product of running a statement must be made available through `OutParameterMetadata`.
Metadata exposure requiring interaction with the database (for example, issuing queries to information schema entities to resolve type properties) cannot be exposed, because methods on `OutParameterMetadata` are expected to be non-blocking.

NOTE: Implementation note: Drivers can use metadata from a static mapping or obtain metadata indexes on connection creation.

The following example shows how to consume `OutParameterMetadata` by using lambdas:

.Retrieving `OutParameterMetadata` information
====
[source,java]
----
// out is a OutParametersMetadata object
out.getParameterMetadatas().forEach(outParameterMetadata -> {

    String name = outParameterMetadata.getName();
    Integer precision = outParameterMetadata.getPrecision();
    Integer scale = outParameterMetadata.getScale();
});
----
====

See the API specification for more details.
