[[overview]]
= Overview

R2DBC provides an API for Java programs to access one or more sources of data.
In the majority of cases, the data source is a relational DBMS and its data is accessed using SQL.
R2DBC drivers are not limited to RDBMS but can be implemented on top of other data sources, including stream-oriented systems and object-oriented systems.
A primary motivation for R2DBC SPI is to provide a standard API for reactive applications to integrate with a wide variety of data sources.

This chapter gives an overview of the API and the key concepts of the R2DBC SPI.
It includes the following topics:

* <<overview.connection>>
* <<overview.connection.discovery>>
* <<overview.connection.url>>
* <<overview.connection.usage>>

[[overview.connection]]
== Establishing a Connection

R2DBC uses the `Connection` interface to define a logical connection API to the underlying data source.
The structure of a connection depends on the actual requirements of a data source and how the driver implements these.

In a typical scenario, an application that uses R2DBC connects to a target data source byusing one of two mechanisms:

* `ConnectionFactories`: R2DBC SPI provides this fully implemented class. It provides `ConnectionFactory` discovery functionality for applications that want to obtain a connection without using a vendor-specific API.
When an application first attempts to connect to a data source, `ConnectionFactories` automatically loads any R2DBC driver found on the classpath by using Java's `ServiceLoader` mechanism.
See <<connections.factory.discovery, ConnectionFactory Discovery>> for the details of how to implement the discovery mechanism for a particular driver.
* `ConnectionFactory`: A `ConnectionFactory` is implemented by a driver and provides access to <<connections,`Connection`>> creation. An application that wants to configure vendor-specific aspects of a driver can use the vendor-specific `ConnectionFactory` creation mechanism to configure a `ConnectionFactory`.

[[overview.connection.discovery]]
=== Using `ConnectionFactory` Discovery

As mentioned <<overview.connection,earlier>>, R2DBC supports the concept of discovery to find an appropriate driver for a connection request.
Providing a `ConnectionFactory` to an application is typically a configuration  infrastructure task.
Applications that wish to bootstrap an R2DBC client typically handle this aspect directly in application code and, so, discovery can become a task for application developers.

`ConnectionFactories` provides two standard mechanisms to bootstrap a `ConnectionFactory`:

* URL-based: R2DBC supports a uniform URL-based configuration scheme with a well-defined structure and well-known configuration properties. URLs are represented as Java `String` and can be passed to `ConnectionFactories` for `ConnectionFactory` lookup.
* Programmatic: In addition to a URL-based configuration, R2DBC provides a programmatic approach so that applications can supply structured configuration options to obtain a `ConnectionFactory`.

In addition to the two preceding methods, R2DBC embraces a mixed mechanism as typical configuration infrastructure mixes URL- and programmatic-based configuration of data sources for enhanced flexibility.
A typical use case is the separation of concerns in which data-source coordinates are supplied by using a URL while login credentials originate from a different configuration source.

[[overview.connection.url]]
=== R2DBC Connection URL

R2DBC defines a standard URL format that is an enhanced form of https://www.ietf.org/rfc/rfc3986.txt[RFC 3986 Uniform Resource Identifier (URI): Generic Syntax] and its amendments supported by Java's `java.net.URI` type.

The following listing shows the syntax Components from https://www.ietf.org/rfc/rfc3986.txt[RFC3986]:

[source,subs="none"]
----
&nbsp;
      URI         = scheme ":" driver [ ":" protocol ] ":" hier-part [ "?" query ] [ "#" fragment ]

      scheme      = "r2dbc" / "r2dbcs"

      driver      = ALPHA *( ALPHA )

      protocol    = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." / ":")

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty

      authority   = [ userinfo "@" ] host [ ":" port ] [ "," host [ ":" port ] ]

      userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )

      host        = IP-literal / IPv4address / reg-name

      port        = *DIGIT

      query       = *( pchar / "/" / "?" )

      fragment    = *( pchar / "/" / "?" )

      pct-encoded = "%" HEXDIG HEXDIG

      pchar       = unreserved / pct-encoded / sub-delims / ":" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="

      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
----

.R2DBC Connection URL
====
[source,subs="none"]
----
&nbsp;
r2dbc:a-driver:pipes://localhost:3306/my_database?locale=en_US
\___/ \______/ \___/   \____________/\__________/\___________/
  |       |      |           |           |           |
scheme  driver  protocol  authority    path        query
----
====

* `scheme`: Identify that the URL is a valid R2DBC URL. Valid schemes are `r2dbc` and `r2dbcs` (configure SSL usage).
* `driver`: Identifier for a driver. R2DBC has no authority over driver identifiers.
* `protocol`: Used as optional protocol information to configure a driver-specific protocol. Protocols can be organized hierarchically and are separated by a colon (`:`).
* `authority`: Contains an endpoint and authorization. The authority may contain a single host or a collection of hostnames and port tuples by separating these with a comma (`,`).
* `path`: (optional) Used as an initial schema or database name.
* `query`: (optional) Used to pass additional configuration options in the form of `String` key-value pairs by using the key name as the option name.
* `fragment`: Unused (reserved for future use).

`ConnectionFactoryOptions.parse(String)` parses a R2DBC URL into `ConnectionFactoryOptions` using standard and optional extended options.
A R2DBC Connection URL is parsed into the following options (by using `ConnectionFactoryOptions` constants):

The following listing shows an example URL:

.R2DBC Connection URL
====
[source]
----
r2dbc:a-driver:pipes://hello:world@localhost:3306/my_database?locale=en_US
----
====

The following table describes the standard options:

.Parsed Standard Options
|===
|Option |URL Part |Value as per Example

|`ConnectionFactoryOptions.SSL`
|`r2dbc`
|Unconfigured.

|`ConnectionFactoryOptions.DRIVER`
|`driver`
|`a-driver`

|`ConnectionFactoryOptions.PROTOCOL`
|`protocol`
|`pipes`

|`ConnectionFactoryOptions.USER`
|User-part of `authority`
|`hello`

|`ConnectionFactoryOptions.PASSWORD`
|Password-part of `authority`
|`world`

|`ConnectionFactoryOptions.HOST`
|Host-part of `authority`
|`localhost`

|`ConnectionFactoryOptions.PORT`
|Port-part of `authority`
|`3306`

|`ConnectionFactoryOptions.DATABASE`
|`path` without the leading `/`
|`my_database`
|===

The following table describes the extended options:

.Parsed Extended Options
|===
|Option |URL Part |Value as per Example

|`locale`
|key-value tuple from `query`
|`en_US`
|===

NOTE: R2DBC defines well-known standard options that are available as runtime constants through `ConnectionFactories`.
Additional options identifiers are created through `Option.valueOf(…)`.

.Obtaining a `ConnectionFactory` using R2DBC URL
====
[source,java]
----
ConnectionFactory factory = ConnectionFactories.get("r2dbc:a-driver:pipes://localhost:3306/my_database?locale=en_US");
----
====

.Obtaining a `ConnectionFactory` using `ConnectionFactoryOptions`
====
[source,java]
----
ConnectionFactoryOptions options = ConnectionFactoryOptions.builder()
    .option(ConnectionFactoryOptions.DRIVER, "a-driver")
    .option(ConnectionFactoryOptions.PROTOCOL, "pipes")
    .option(ConnectionFactoryOptions.HOST, "localhost")
    .option(ConnectionFactoryOptions.PORT, 3306)
    .option(ConnectionFactoryOptions.DATABASE, "my_database")
    .option(Option.valueOf("locale"), "en_US")
    .build();

ConnectionFactory factory = ConnectionFactories.get(options);
----
====

[[overview.connection.usage]]
== Running SQL and Retrieving Results

Once a connection has been established, an application using the R2DBC SPI can execute queries and updates against the connected database.
The R2DBC SPI provides a text-based command interface to the most commonly used features of SQL databases.
R2DBC driver implementations may expose additional functionality in a non-standard way.

Applications use methods in the `Connection` interface to specify transaction attributes and create `Statement` or `Batch` objects.
These statements are used to execute SQL and retrieve results and allow for binding values to parameter bind markers.
The `Result` interface encapsulates the results of an SQL query.
Statements may also be batched, allowing an application to submit multiple commands to a database as a single unit of execution.

