[[results]]
= Results

This section explains the `Result` interface and the related `Row` interface. It also describes related topics, including result consumption.

[[results.characteristics]]
== Result Characteristics

`Result` objects are forward-only and read-only objects that allow consumption of two result types:

* Tabular results
* Update count

Results move forward from the first `Row` to the last one. After emitting the last row, a `Result` object gets invalidated and rows from the same `Result` object can no longer be consumed.
Rows contained in the result depend on how the underlying database materializes the results.
That is, it contains the rows that satisfy the query at either the time the query is run or as the rows are retrieved.
An R2DBC driver can obtain a `Result` either directly or by using cursors.

`Result` reports the number of rows affected for SQL statements, such as updates for SQL Data Manipulation Language (DML) statements.
The update count can be empty for statements that do not modify rows.
After emitting the update count, a `Result` object gets invalidated and rows from the same `Result` object can no longer be consumed.
The following example shows how to get a count of updated rows:

.Consuming an update count
====
[source,java]
----
// result is a Result object
Publisher<Integer> rowsUpdated = result.getRowsUpdated();
----
====

The streaming nature of a result allows consumption of either tabular results or an update count.
Depending on how the underlying database materializes results, an R2DBC driver can lift this limitation.

A `Result` object is emitted for each statement result in a forward-only direction.

[[results.creating]]
== Creating `Result` Objects

A `Result` object is most often created as the result of running a `Statement` object.
The `Statement.execute()` method returns a `Publisher` that emits a `Result` objects as the result of running the statement.
The following example shows how to create a `Result` object:

.Creating a `Result` object
====
[source,java]
----
// connection is a Connection object
Statement statement = connection.createStatement("SELECT title, author FROM books");
Publisher<? extends Result> results = statement.execute();
----
====

The `Result` object emits a `Row` object for each row in the `books` table (which contains two columns: `title` and `author`).
The following sections detail how these rows and columns can be consumed.

[[results.cursor]]
=== Cursor Movement

`Result` objects can be backed by direct results (that is, a query that returns results directly) or by cursors.
By consuming `Row` objects, an R2DBC driver advances the cursor position.
Thus, external cursor navigation is not possible.

Canceling subscription of tabular results stops cursor reads and releases any resources associated with the `Result` object.

[[rows]]
== Rows

A `Row` object represents a single row of tabular results.

[[row.values]]
=== Retrieving Values

The `Result` interface provides a `map(…)` method for retrieving values from `Row` objects.
The `map` method accepts a `BiFunction` (also referred to as mapping function) object that accepts `Row` and `RowMetadata`.
The mapping function is called upon row emission with `Row` and `RowMetadata` objects.
A `Row` is only valid during the mapping function callback and is invalid outside of the mapping function callback.
Thus, `Row` objects must be entirely consumed by the mapping function.

The <<rowmetadata>> section contains additional details on metadata.

[[row.methods]]
== Interface Methods

The following methods are available on the `Row` interface:

* `Object get(int)`
* `Object get(String)`
* `<T> T get(int, Class<T>)`
* `<T> T get(String, Class<T>)`

`get(int[, Class])` methods accept column indexes starting at 0, `get(String[, Class])` methods accept column name aliases as they are represented in the result.
Column names used as input to the `get` methods are case insensitive.
Column names do not necessarily reflect the column names as they are in the underlying tables but, rather, how columns are represented (for example, aliased) in the result.
The following example shows how to create and consume a `Row` by using its index:

The following methods have **deprecated** on the `Row` interface:

* `Object get(Object)`
* `<T> T get(Object, Class<T>)`

Both `get(Object[, Class])` methods will be remove before the release of 0.8.0.RELEASE.

.Creating and Consuming a `Row` using its index
====
[source,java]
----
// result is a Result object
Publisher<Object> values = result.map((row, rowMetadata) -> row.get(0));
----
====

The following example shows how to create and consume a `Row` by using its column name:

.Creating and Consuming a `Row` by using its column name
====
[source,java]
----
// result is a Result object
Publisher<Object> titles = result.map((row, rowMetadata) -> row.get("title"));
----
====

Calling `get` without specifying a target type returns a suitable value representation according to <<datatypes.mapping>>.
When you specify a target type, the R2DBC driver tries to convert the value to the target type.
The following example shows how to creat and consume a `Row` with type conversion:

.Creating and Consuming a `Row` with type conversion
====
[source,java]
----
// result is a Result object
Publisher<String> values = result.map((row, rowMetadata) -> row.get(0, String.class));
----
====

You can also consume multiple columns from a `Row`, as the following example shows:

.Consuming multiple columns from a `Row`
====
[source,java]
----
// result is a Result object
Publisher<Book> values = result.map((row, rowMetadata) -> {
    String title = row.get("title", String.class);
    String author = row.get("author", String.class);

    return new Book(title, author);
});
----
====

When the column value in the database is SQL `NULL`, it can be returned to the Java application as `null`.

NOTE: `null` values cannot be returned as Reactive Streams values and must be wrapped for subsequent usage.

NOTE: Invalidating a `Row` does *not* release `Blob` and `Clob` objects that were obtained from the `Row`. These objects remain valid for at least the duration of the transaction in which they were created, unless their `discard()` method is called.
