[[results]]
= Results

This section explains the `Result` interface and the related `Gettable` interface.
It also describes related topics, including result consumption.

[[results.characteristics]]
== Result Characteristics

`Result` objects are forward-only and read-only objects that allow consumption of the following result types:

* Update count
* <<rows,Tabular results>>
* <<out-parameters,OUT parameters>>

Results move forward from the first `Row` to the last one.
After emitting the last row, drivers can expose out parameters by emitting `OutParameters`.
After that, a `Result` object gets invalidated and results from the same `Result` object can no longer be consumed.
Rows and parameters contained in the result depend on how the underlying database materializes the results.
That is, it contains the rows that satisfy the query at either the time the query is run or as the rows are retrieved.
An R2DBC driver can obtain a `Result` either directly or by using cursors.

`Result` reports the number of rows affected for SQL statements, such as updates for SQL Data Manipulation Language (DML) statements.
The update count can be empty for statements that do not modify rows.
After emitting the update count, a `Result` object gets invalidated and rows from the same `Result` object can no longer be consumed.
The following example shows how to get a count of updated rows:

.Consuming an update count
====
[source,java]
----
// result is a Result object
Publisher<Integer> rowsUpdated = result.getRowsUpdated();
----
====

`Result` represens a stream of result segements.
Due to its nature, a result allows consumption of either tabular results, out parameters, or an update count through `map(…)` respective `getRowsUpdated(…)` but not both.
Depending on how the underlying database materializes results, an R2DBC driver can lift this limitation.

A `Result` object is emitted for each statement result in a forward-only direction.
A statement can lead to multiple `Result` objects caused by either multiple bindings or by running a statement that materializes multiple result sets.

<<<

[[results.creating]]
== Creating `Result` Objects

A `Result` object is created as the result of running a `Statement` object.
The `Statement.execute()` method returns a `Publisher` that emits `Result` objects as the result of running the statement.
The following example shows how to create a `Result` object:

.Creating a `Result` object
====
[source,java]
----
// connection is a Connection object
Statement statement = connection.createStatement("SELECT title, author FROM books");
Publisher<? extends Result> results = statement.execute();
----
====

The `Result` object emits a `Row` object for each row in the `books` table (which contains two columns: `title` and `author`).
The following sections detail how these rows and columns can be consumed.

[[results.cursor]]
=== Cursor Movement

`Result` objects can be backed by direct results (that is, a query that returns results directly) or by cursors.
By consuming `Row` objects, an R2DBC driver advances the cursor position.
Thus, external cursor navigation is not possible.

Canceling subscription of tabular results stops cursor reads and releases any resources associated with the `Result` object.

<<<
