[[rowmetadata]]
= Column and Row Metadata

The `RowMetadata` interface is implemented by R2DBC drivers to provide information about tabular results.
It is used primarily by libraries and applications to determine the properties of a row and its columns.

In cases where the result properties of an SQL statement are unknown until it is run, the `RowMetadata` can be used to determine the actual properties of a row.

`RowMetadata` exposes `ColumnMetadata` for each column in the result.
Drivers should provide `ColumnMetadata` on a best-effort basis.
Column metadata is typically a by-product of statement execution.
The amount of available information is vendor-dependent.
Metadata retrieval can require additional lookups (internal queries) to provide a complete metadata descriptor.
Issuing queries during result processing conflicts with the streaming nature of R2DBC.
Consequently, `ColumnMetadata` declares two sets of methods: methods that must be implemented and methods that can optionally be implemented by drivers.

== Obtaining a `RowMetadata` Object

A `RowMetadata` object is created during tabular results consumption through `Result.map(…)`.
It is created for each row.The following example illustrates retrieval and usage by using an anonymous inner class:

.Using `RowMetadata` and retrieving `ColumnMetadata`
====
[source,java]
----
// result is a Result object
result.map(new BiFunction<Row, RowMetadata, Object>() {

    @Override
    public Object apply(Row row, RowMetadata rowMetadata) {
        ColumnMetadata my_column = rowMetadata.getColumnMetadata("my_column");
        Nullability nullability = my_column.getNullability();
        // …
    }
});
----
====

[[columnmetadata]]
== Retrieving `ColumnMetadata`

`RowMetadata` methods are used to retrieve metadata for a single column or all columns.

* `getColumnMetadata(int)` returns the `ColumnMetadata` by using a zero-based index.
See <<compliance.guidelines>>.
* `getColumnMetadata(String)` returns the `ColumnMetadata` by using the column name.
* `getColumnMetadatas()` returns an unmodifiable collection of `ColumnMetadata` objects.

== Retrieving General Information for a Column

`ColumnMetadata` declares methods to access column metadata on a best-effort basis.
Column metadata that is available as a by-product of running a statement must be made available through `ColumnMetadata`.
Metadata exposure requiring interaction with the database (for example, issuing queries to information schema entities to resolve type properties) cannot be exposed, because methods on `ColumnMetadata` are expected to be non-blocking.

NOTE: Implementation note: Drivers can use metadata from a static mapping or obtain metadata indexes on connection creation.

The following example shows how to consume `ColumnMetadata` by using lambdas:

.Retrieving `ColumnMetadata` information
====
[source,java]
----
// row is a RowMetadata object
row.getColumnMetadatas().forEach(columnMetadata -> {

    String name = columnMetadata.getName();
    Integer precision = columnMetadata.getPrecision();
    Integer scale = columnMetadata.getScale();
});
----
====

See the API specification for more details.
