[[rows]]
== Rows

A `Row` object represents a single row of tabular results.

[[row.values]]
=== Retrieving Values

The `Result` interface provides a `map(…)` method for retrieving values from `Row` objects.
The `map` method accepts a `BiFunction` (also referred to as mapping function) object that accepts `Row` and `RowMetadata`.
The mapping function is called upon row emission with `Row` and `RowMetadata` objects.
A `Row` is only valid during the mapping function callback and is invalid outside of the mapping function callback.
Thus, `Row` objects must be entirely consumed by the mapping function.
The overloaded `map` method accepting a `Function` object for `Readable` can be called with either `Row` or `OutParameters` objects or vendor-specific extensions.

The <<rowmetadata>> section contains additional details on metadata.

[[row.methods]]
== Interface Methods

The following methods are available on the `Row` interface:

* `Object get(int)` (inherited from `Readable`)
* `Object get(String)` (inherited from `Readable`)
* `<T> T get(int, Class<T>)` (inherited from `Readable`)
* `<T> T get(String, Class<T>)` (inherited from `Readable`)
* `RowMetadata getMetadata()`

`get(int[, Class])` methods accept column indexes starting at `0`, `get(String[, Class])` methods accept column name aliases as they are represented in the result.
Column names used as input to the `get` methods are case-insensitive.
Column names do not necessarily reflect the column names as they are in the underlying tables but, rather, how columns are represented (for example, aliased) in the result.
The following example shows how to create and consume a `Row` by using its index:

.Creating and Consuming a `Row` by obtaining a column by index
====
[source,java]
----
// result is a Result object
Publisher<Object> values = result.map((row, rowMetadata) -> row.get(0));
----
====

The following example shows how to create and consume a `Row` by using its column name:

.Creating and Consuming a `Row` by obtaining a column by name
====
[source,java]
----
// result is a Result object
Publisher<Object> titles = result.map((row, rowMetadata) -> row.get("title"));
----
====

Calling `get` without specifying a target type returns a suitable value representation according to <<datatypes.mapping>>.
When specifying a target type, the R2DBC driver tries to convert the value to the target type.
The following example shows how to create and consume a `Row` with type conversion:

.Creating and Consuming a `Row` with type conversion
====
[source,java]
----
// result is a Result object
Publisher<String> values = result.map((row, rowMetadata) -> row.get(0, String.class));
----
====

You can also consume multiple columns from a `Row`, as the following example shows:

.Consuming multiple columns from a `Row`
====
[source,java]
----
// result is a Result object
Publisher<Book> values = result.map((row, rowMetadata) -> {
    String title = row.get("title", String.class);
    String author = row.get("author", String.class);

    return new Book(title, author);
});
----
====

When the column value in the database is SQL `NULL`, it can be returned to the Java application as `null`.

NOTE: `null` values cannot be returned as Reactive Streams values and must be wrapped for subsequent usage.

NOTE: Invalidating a `Row` does *not* release `Blob` and `Clob` objects that were obtained from the `Row`.
These objects remain valid for at least the duration of the transaction in which they were created, unless their `discard()` method is called.
