[[transactions]]
= Transactions

Transactions are used to provide data integrity, isolation, correct application semantics, and a consistent view of data during concurrent database access.
All R2DBC-compliant drivers are required to provide transaction support.
Transaction management in the R2DBC SPI reflects SQL concepts:

* Transaction Boundaries
* Auto-commit mode
* Transaction isolation levels
* Savepoints

This section explains transaction semantics associated with a single `Connection` object.

[[transactions.boundaries]]
== Transaction Boundaries

Transactions begin implicitly or explicitly.
Implicit transactions begin by starting SQL execution when a `Connection` is in auto-commit mode (which is the default for newly created connections).
Alternatively, explicit transactions begin by invoking the `beginTransaction()` method that disables auto-commit mode.
Transactions are started by either the R2DBC driver or its underlying database.

Newly started transactions inherit attributes from the connection such as <<transactions.isolation,Isolation Level>>. Starting a transaction using `beginTransaction(TransactionDefinition)` allows R2DBC drivers to compute a transaction definition from any plurality of attributes before starting the actual transaction. A driver may apply optimizations such as reduction of database roundtrips. Attributes retrieved from `TransactionDefinition` are only valid during the transaction.

[[transactions.transaction-definition]]
=== TransactionDefinition Interface

The `io.r2dbc.spi.TransactionDefinition` interface provides a mechanism for drivers to obtain transaction attributes when starting a transaction using a vendor-neutral API. R2DBC drivers query objects implementing the interface for supported attributes. The interface defines attribute constants for commonly supported attributes such as Isolation Level, Transaction Mutability, Transaction Name, and Lock Wait Timeout. Drivers may specify and query additional attributes.

[[transactions.transaction-definition.usage]]
==== Usage

Starting a transaction using a `TransactionDefinition` object allows R2DBC drivers to use the definition object as callback to query for transactional attributes.
The following example shows how to start a transaction:

.Starting a transaction using `TransactionDefinition`.
====
[source,java]
----
// connection is a Connection object
// definition is a TransactionDefinition object
Publisher<Void> begin = connection.beginTransaction(definition);
----                                    
====

NOTE: Drivers may reject attributes based on the connection configuration. An example would be the use of read-write transactions with connections in read-only mode.

[[transactions.transaction-definition.methods]]
==== Interface Methods

The following methods are available on the `TransactionDefinition` interface:

* `getAttribute`

[[transactions.transaction-definition.get-attribute]]
==== The `getAttribute` Method

R2DBC drivers invoke the `getAttribute` method to query for transaction attributes. Attributes that have no configuration value attached are considered unconfigured and therefore represented with a `null` value. The value type follows the actual attribute identified by a `Option` constant.  

[[transactions.auto-commit]]
== Auto-commit Mode

A `ConnectionFactory` creates new `Connection` objects with auto-commit mode enabled, unless specified otherwise through connection configuration options.
The `Connection` interface provides two methods to interact with auto-commit mode:

* `setAutoCommit`
* `isAutoCommit`

R2DBC applications should change auto-commit mode by invoking the `setAutoCommit` method instead of executing SQL commands to change the connection configuration.
If the value of auto-commit is changed during an active transaction, the current transaction is committed.
If `setAutoCommit` is called and the value for auto-commit is not changed from its current value, this is treated as a no-op.

Changing auto-commit mode typically engages database activity.
Therefore, the method returns a `Publisher`.
Querying auto-commit mode is typically a local operation that involves driver state without database communication.

When auto-commit is disabled, you must explicitly start and clean up each transaction by calling the `Connection` methods `beginTransaction` and `commitTransaction` (or `rollbackTransaction`), respectively.

This is appropriate for cases where transaction management is being done in a layer above the driver, such as:

* The application needs to group multiple SQL statements into a single transaction.
* An application container manages the transaction state.

[[transactions.isolation]]
== Transaction Isolation

Transaction isolation levels define the level of visibility ("`isolation`") for statements that are run within a transaction.
They impact concurrent access while multiple transactions are active.

The default transaction level for a `Connection` object is vendor-specific and determined by the driver that supplied the connection.
Typically, it defaults to the transaction level supported by the underlying data source.

The `Connection` interface provides two methods to interact with transaction isolation levels:

* `setTransactionIsolationLevel`
* `getTransactionIsolationLevel`

R2DBC applications should change transaction isolation levels by invoking the `setTransactionIsolationLevel` method instead of running SQL commands to change the connection configuration.

Changing transaction isolation levels typically involves database activity.
Therefore, the method returns a `Publisher`.
Changing an isolation level during an active transaction results in implementation-specific behavior.
Querying transaction isolation levels is typically a local operation that involves driver state without database communication.
The return value of the method `getTransactionIsolationLevel` reflects the current isolation level when it actually occurs.
`IsolationLevel` is an extensible runtime-constant so drivers may define their own isolation levels.
A driver may not support transaction levels.
Calling `getTransactionIsolationLevel` results in returning vendor-specific `IsolationLevel` object.

=== Performance Considerations

When you increase the transaction isolation level, databases typically require more locking and resource overhead to ensure isolation level semantics.
This, in turn, lowers the degree of concurrent access that can be supported.
As a result, applications may see degraded performance when they use higher transaction isolation levels.
For this reason, a transaction manager, whether it is the application itself or part of the application container, should weigh the need for data consistency against the requirements for performance when determining which transaction isolation level is appropriate.

[[transactions.savepoints]]
== Savepoints

Savepoints provide a fine-grained control mechanism by marking intermediate points within a transaction.
Once a savepoint has been created, a transaction can be rolled back to that savepoint without affecting preceding work.

=== Working with Savepoints

The `Connection` interface defines methods to interact with savepoints:

* `createSavepoint`
* `releaseSavepoint`
* `rollbackTransactionToSavepoint`

Savepoints are created during an active transaction and are valid only as long as the transaction is active.
You can use the `createSavepoint` method to set a savepoint within the current transaction.
A transaction is started if `createSavepoint` is invoked and there is no active transaction (switching the connection to disabled auto-commit mode).
The `rollbackTransactionToSavepoint` method is used to roll back work to a previous savepoint without rolling back the entire transaction.
the following example shows how to roll back a transaction to a savepoint:

.Rolling back a transaction to a savepoint
====
[source,java]
----
// connection is a Connection object
Publisher<Void> begin = connection.beginTransaction();

Publisher<Void> insert1 = connection.createStatement("INSERT INTO books VALUES ('John Doe')").execute();

Publisher<Void> savepoint = connection.createSavepoint("savepoint");

Publisher<Void> insert2 = connection.createStatement("INSERT INTO books VALUES ('Jane Doe')").execute();

…

Publisher<Void> partialRollback = connection.rollbackTransactionToSavepoint("savepoint");

…

Publisher<Void> commit = connection.commit();

// publishers are materialized in the order: begin, insert1, savepoint, insert2, partialRollback, commit
----
====

Drivers that do not support savepoint creation and rolling back to a savepoint should throw an `UnsupportedOperationException` to indicate these features are not supported.

<<<

=== Releasing a Savepoint

Savepoints allocate resources on the databases, and some vendors may require releasing a savepoint to dispose resources.
The `Connection` interface  defines the `releaseSavepoint` method to release savepoints that are no longer needed.

Savepoints that were created during a transaction are released and are invalidated when the transaction is committed or when the entire transaction is rolled back.
Rolling a transaction back to a savepoint automatically releases it. A rollback also invalidates any other savepoints that were created after the savepoint in question.

Calling `releaseSavepoint` for drivers that do not support savepoint release results in a no-op.
