[[wrapped]]
= Wrapped Interface

The `Wrapped` interface provides a mechanism for users to access an instance of a resource which has been wrapped and for implementors to expose wrapped resources. This mechanism helps to eliminate the need to use non-standard means to access vendor-specific resources.

[[wrapped.usage]]
== Usage

A wrapper for a R2DBC SPI type is expected to implement the `Wrapped` interface so that callers can extract the original instance. Any R2DBC SPI interface type can be wrapped.

.Wrapping a `Connection` and exposing the underlying resource.
====
[source,java]
----
class ConnectionWrapper implements Connection, Wrapped<Connection> {

    private final Connection wrapped;

    @Override
    public Connection unwrap() {
        return this.wrapped;
    }

    // constructors and implementation methods omitted for brevity.
}
----
====

[[wrapped.methods]]
== Interface Methods

The following methods are available on the `Wrapped` interface:

* `unwrap`

[[wrapped.unwrap]]
== `unwrap` Method

The `unwrap` method is used to return an object that implements the specified interface allowing access to vendor-specific methods.
The returned object may either be the object found to implement the specified interface or a wrapper for that object.
Wrappers can be unwrapped recursively.

.Unwrapping a wrapped object.
====
[source,java]
----
// connection is a Connection object implementing Wrapped

if (connection instanceof Wrapped) {
    connection = ((Wrapped<Connection>) connection).unwrap();
}
----
====
