# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, 0.8.x, 0.9.x ]

jobs:
  build:
    if: github.repository == 'r2dbc/r2dbc-spi'
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            include:
                - os: ubuntu-latest
                  mvn: ./mvnw
                - os: windows-latest
                  mvn: mvn
                - os: macos-latest
                  mvn: ./mvnw
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
        CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
      run: ${{ matrix.mvn }} -B deploy -P snapshot -s settings.xml
